// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RobotEyes

#include "ui.h"
#include "ui_helpers.h"
#include "ui_PillShape.h"

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
    ui_PillShape_screen_init();
    lv_disp_load_scr(ui_PillShape);
}

void ui_destroy( void )
{
    ui_PillShape_screen_destroy();
}
