// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RobotEyes
// Screen: ANGRY - Narrowed eyes, red pupils, eyebrows

#include "ui.h"

lv_obj_t *ui_Screen3 = NULL;

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x1A0000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Eye (white circle) ----
    lv_obj_t *obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 110);
    lv_obj_set_height(obj, 110);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Eye (white circle) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 110);
    lv_obj_set_height(obj, 110);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Lid (black bar covering top of eye - makes it look angry/narrowed) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 130);
    lv_obj_set_height(obj, 50);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -90);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x1A0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Lid (covers top of right eye) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 130);
    lv_obj_set_height(obj, 50);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -90);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x1A0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Pupil (red) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 40);
    lv_obj_set_height(obj, 40);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -50);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFF2222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Pupil (red) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 40);
    lv_obj_set_height(obj, 40);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -50);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFF2222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Eyebrow (red, angled) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 120);
    lv_obj_set_height(obj, 12);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -130);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(obj, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Eyebrow (red, angled opposite) ----
    obj = lv_obj_create(ui_Screen3);
    lv_obj_set_width(obj, 120);
    lv_obj_set_height(obj, 12);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -130);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(obj, -150, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Frown (arc flipped) ----
    lv_obj_t *arc = lv_arc_create(ui_Screen3);
    lv_obj_set_width(arc, 100);
    lv_obj_set_height(arc, 100);
    lv_obj_set_x(arc, 0);
    lv_obj_set_y(arc, 80);
    lv_obj_set_align(arc, LV_ALIGN_CENTER);
    lv_arc_set_rotation(arc, 180);
    lv_arc_set_bg_angles(arc, 210, 330);
    lv_arc_set_value(arc, 0);
    lv_obj_set_style_arc_width(arc, 5, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_color_hex(0xFF4444), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);

    // ---- State Label ----
    lv_obj_t *label = lv_label_create(ui_Screen3);
    lv_label_set_text(label, "ANGRY");
    lv_obj_set_style_text_color(label, lv_color_hex(0xFF4444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, -20);
}

void ui_Screen3_screen_destroy(void)
{
    if (ui_Screen3) lv_obj_del(ui_Screen3);
    ui_Screen3 = NULL;
}
