// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RobotEyes
// Screen: SLEEPING - Closed eyes, ZZZ

#include "ui.h"

lv_obj_t *ui_Screen6 = NULL;

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x000005), LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Closed Eye (horizontal line) ----
    lv_obj_t *obj = lv_obj_create(ui_Screen6);
    lv_obj_set_width(obj, 110);
    lv_obj_set_height(obj, 8);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Closed Eye (horizontal line) ----
    obj = lv_obj_create(ui_Screen6);
    lv_obj_set_width(obj, 110);
    lv_obj_set_height(obj, 8);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Eyelash arc (gentle curve above closed eye) ----
    lv_obj_t *arc = lv_arc_create(ui_Screen6);
    lv_obj_set_width(arc, 100);
    lv_obj_set_height(arc, 50);
    lv_obj_set_x(arc, -65);
    lv_obj_set_y(arc, -75);
    lv_obj_set_align(arc, LV_ALIGN_CENTER);
    lv_arc_set_rotation(arc, 180);
    lv_arc_set_bg_angles(arc, 180, 360);
    lv_arc_set_value(arc, 0);
    lv_obj_set_style_arc_width(arc, 3, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_color_hex(0x888899), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);

    // ---- Right Eyelash arc ----
    arc = lv_arc_create(ui_Screen6);
    lv_obj_set_width(arc, 100);
    lv_obj_set_height(arc, 50);
    lv_obj_set_x(arc, 65);
    lv_obj_set_y(arc, -75);
    lv_obj_set_align(arc, LV_ALIGN_CENTER);
    lv_arc_set_rotation(arc, 180);
    lv_arc_set_bg_angles(arc, 180, 360);
    lv_arc_set_value(arc, 0);
    lv_obj_set_style_arc_width(arc, 3, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_color_hex(0x888899), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);

    // ---- Z (small) ----
    lv_obj_t *label = lv_label_create(ui_Screen6);
    lv_label_set_text(label, "z");
    lv_obj_set_style_text_color(label, lv_color_hex(0x8888FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(label, 110);
    lv_obj_set_y(label, -100);
    lv_obj_set_align(label, LV_ALIGN_CENTER);

    // ---- Z (medium) ----
    label = lv_label_create(ui_Screen6);
    lv_label_set_text(label, "Z");
    lv_obj_set_style_text_color(label, lv_color_hex(0x6666DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(label, 120);
    lv_obj_set_y(label, -130);
    lv_obj_set_align(label, LV_ALIGN_CENTER);

    // ---- Z (large) ----
    label = lv_label_create(ui_Screen6);
    lv_label_set_text(label, "Z");
    lv_obj_set_style_text_color(label, lv_color_hex(0x4444BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_x(label, 128);
    lv_obj_set_y(label, -165);
    lv_obj_set_align(label, LV_ALIGN_CENTER);

    // ---- Gentle Mouth (small thin line) ----
    obj = lv_obj_create(ui_Screen6);
    lv_obj_set_width(obj, 40);
    lv_obj_set_height(obj, 4);
    lv_obj_set_x(obj, 0);
    lv_obj_set_y(obj, 100);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x666688), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- State Label ----
    label = lv_label_create(ui_Screen6);
    lv_label_set_text(label, "SLEEPING");
    lv_obj_set_style_text_color(label, lv_color_hex(0x6666BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, -20);
}

void ui_Screen6_screen_destroy(void)
{
    if (ui_Screen6) lv_obj_del(ui_Screen6);
    ui_Screen6 = NULL;
}
