// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RobotEyes

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5 (SURPRISED)
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t *ui_Screen5;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
