// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: RobotEyes
// Screen: SAD - Droopy eyes, tears, frown

#include "ui.h"

lv_obj_t *ui_Screen4 = NULL;

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000008), LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Eye ----
    lv_obj_t *obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 110);
    lv_obj_set_height(obj, 110);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Eye ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 110);
    lv_obj_set_height(obj, 110);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -60);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Droopy Lid (covers upper-outer part of left eye) ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 80);
    lv_obj_set_height(obj, 45);
    lv_obj_set_x(obj, -45);
    lv_obj_set_y(obj, -88);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x000008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(obj, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Droopy Lid ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 80);
    lv_obj_set_height(obj, 45);
    lv_obj_set_x(obj, 85);
    lv_obj_set_y(obj, -88);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x000008), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(obj, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Left Pupil (blue) ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 40);
    lv_obj_set_height(obj, 40);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -55);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Right Pupil (blue) ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 40);
    lv_obj_set_height(obj, 40);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -55);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Tear drop 1 (left eye) ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 16);
    lv_obj_set_height(obj, 22);
    lv_obj_set_x(obj, -50);
    lv_obj_set_y(obj, 10);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Tear drop 2 (smaller, below first) ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 10);
    lv_obj_set_height(obj, 14);
    lv_obj_set_x(obj, -50);
    lv_obj_set_y(obj, 30);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Sad Eyebrows (angled up toward center) ----
    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 100);
    lv_obj_set_height(obj, 8);
    lv_obj_set_x(obj, -65);
    lv_obj_set_y(obj, -130);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x6688BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(obj, -100, LV_PART_MAIN | LV_STATE_DEFAULT);

    obj = lv_obj_create(ui_Screen4);
    lv_obj_set_width(obj, 100);
    lv_obj_set_height(obj, 8);
    lv_obj_set_x(obj, 65);
    lv_obj_set_y(obj, -130);
    lv_obj_set_align(obj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_radius(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(obj, lv_color_hex(0x6688BB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_angle(obj, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ---- Sad Mouth (frown arc) ----
    lv_obj_t *arc = lv_arc_create(ui_Screen4);
    lv_obj_set_width(arc, 80);
    lv_obj_set_height(arc, 80);
    lv_obj_set_x(arc, 0);
    lv_obj_set_y(arc, 100);
    lv_obj_set_align(arc, LV_ALIGN_CENTER);
    lv_arc_set_rotation(arc, 180);
    lv_arc_set_bg_angles(arc, 210, 330);
    lv_arc_set_value(arc, 0);
    lv_obj_set_style_arc_width(arc, 5, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, lv_color_hex(0x6688BB), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, 0, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);

    // ---- State Label ----
    lv_obj_t *label = lv_label_create(ui_Screen4);
    lv_label_set_text(label, "SAD");
    lv_obj_set_style_text_color(label, lv_color_hex(0x4488FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(label, LV_ALIGN_BOTTOM_MID, 0, -20);
}

void ui_Screen4_screen_destroy(void)
{
    if (ui_Screen4) lv_obj_del(ui_Screen4);
    ui_Screen4 = NULL;
}
